FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install --prod

COPY microservices ./microservices
COPY services ./services
COPY shared ./shared

EXPOSE 3001 3002 3003 3004 3005

CMD ["node", "index.js"]
