FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN npm install -g pnpm && pnpm install --prod

COPY microservices/api-gateway ./microservices/api-gateway
COPY shared ./shared
COPY frontend/dist ./frontend/dist

EXPOSE 3000

CMD ["node", "microservices/api-gateway/index.js"]
